# Generated by Django 5.2.8 on 2025-11-08 22:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser positivo.')])),
                ('ambientes', models.PositiveSmallIntegerField(default=1)),
                ('dormitorios', models.PositiveSmallIntegerField(default=1)),
                ('banos', models.PositiveSmallIntegerField(default=1)),
                ('superficie_total', models.DecimalField(decimal_places=2, help_text='m² totales', max_digits=8)),
                ('superficie_cubierta', models.DecimalField(decimal_places=2, help_text='m² cubiertos', max_digits=8)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('numero_whatsapp', models.CharField(blank=True, help_text='Número de contacto para WhatsApp (incluir código de país)', max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Propiedad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades_fotos/')),
                ('es_principal', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.propiedad')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de Propiedad',
                'ordering': ['-es_principal'],
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipopropiedad'),
        ),
    ]
